/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PayableOverrides,
  PopulatedTransaction,
  Signer,
  utils,
} from 'ethers'
import type {
  FunctionFragment,
  Result,
  EventFragment,
} from '@ethersproject/abi'
import type { Listener, Provider } from '@ethersproject/providers'
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from './common'

export interface Erc721PegInterface extends utils.Interface {
  functions: {
    'adminEmergencyWithdraw(address[],uint256[][],address)': FunctionFragment
    'bridge()': FunctionFragment
    'deposit(address[],uint256[][],address)': FunctionFragment
    'depositsActive()': FunctionFragment
    'onERC721Received(address,address,uint256,bytes)': FunctionFragment
    'onMessageReceived(address,bytes)': FunctionFragment
    'owner()': FunctionFragment
    'palletAddress()': FunctionFragment
    'renounceOwnership()': FunctionFragment
    'setBridgeAddress(address)': FunctionFragment
    'setDepositsActive(bool)': FunctionFragment
    'setPalletAddress(address)': FunctionFragment
    'setWithdrawalsActive(bool)': FunctionFragment
    'transferOwnership(address)': FunctionFragment
    'withdrawalsActive()': FunctionFragment
  }

  getFunction(
    nameOrSignatureOrTopic:
      | 'adminEmergencyWithdraw'
      | 'bridge'
      | 'deposit'
      | 'depositsActive'
      | 'onERC721Received'
      | 'onMessageReceived'
      | 'owner'
      | 'palletAddress'
      | 'renounceOwnership'
      | 'setBridgeAddress'
      | 'setDepositsActive'
      | 'setPalletAddress'
      | 'setWithdrawalsActive'
      | 'transferOwnership'
      | 'withdrawalsActive'
  ): FunctionFragment

  encodeFunctionData(
    functionFragment: 'adminEmergencyWithdraw',
    values: [
      PromiseOrValue<string>[],
      PromiseOrValue<BigNumberish>[][],
      PromiseOrValue<string>
    ]
  ): string
  encodeFunctionData(functionFragment: 'bridge', values?: undefined): string
  encodeFunctionData(
    functionFragment: 'deposit',
    values: [
      PromiseOrValue<string>[],
      PromiseOrValue<BigNumberish>[][],
      PromiseOrValue<string>
    ]
  ): string
  encodeFunctionData(
    functionFragment: 'depositsActive',
    values?: undefined
  ): string
  encodeFunctionData(
    functionFragment: 'onERC721Received',
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BytesLike>
    ]
  ): string
  encodeFunctionData(
    functionFragment: 'onMessageReceived',
    values: [PromiseOrValue<string>, PromiseOrValue<BytesLike>]
  ): string
  encodeFunctionData(functionFragment: 'owner', values?: undefined): string
  encodeFunctionData(
    functionFragment: 'palletAddress',
    values?: undefined
  ): string
  encodeFunctionData(
    functionFragment: 'renounceOwnership',
    values?: undefined
  ): string
  encodeFunctionData(
    functionFragment: 'setBridgeAddress',
    values: [PromiseOrValue<string>]
  ): string
  encodeFunctionData(
    functionFragment: 'setDepositsActive',
    values: [PromiseOrValue<boolean>]
  ): string
  encodeFunctionData(
    functionFragment: 'setPalletAddress',
    values: [PromiseOrValue<string>]
  ): string
  encodeFunctionData(
    functionFragment: 'setWithdrawalsActive',
    values: [PromiseOrValue<boolean>]
  ): string
  encodeFunctionData(
    functionFragment: 'transferOwnership',
    values: [PromiseOrValue<string>]
  ): string
  encodeFunctionData(
    functionFragment: 'withdrawalsActive',
    values?: undefined
  ): string

  decodeFunctionResult(
    functionFragment: 'adminEmergencyWithdraw',
    data: BytesLike
  ): Result
  decodeFunctionResult(functionFragment: 'bridge', data: BytesLike): Result
  decodeFunctionResult(functionFragment: 'deposit', data: BytesLike): Result
  decodeFunctionResult(
    functionFragment: 'depositsActive',
    data: BytesLike
  ): Result
  decodeFunctionResult(
    functionFragment: 'onERC721Received',
    data: BytesLike
  ): Result
  decodeFunctionResult(
    functionFragment: 'onMessageReceived',
    data: BytesLike
  ): Result
  decodeFunctionResult(functionFragment: 'owner', data: BytesLike): Result
  decodeFunctionResult(
    functionFragment: 'palletAddress',
    data: BytesLike
  ): Result
  decodeFunctionResult(
    functionFragment: 'renounceOwnership',
    data: BytesLike
  ): Result
  decodeFunctionResult(
    functionFragment: 'setBridgeAddress',
    data: BytesLike
  ): Result
  decodeFunctionResult(
    functionFragment: 'setDepositsActive',
    data: BytesLike
  ): Result
  decodeFunctionResult(
    functionFragment: 'setPalletAddress',
    data: BytesLike
  ): Result
  decodeFunctionResult(
    functionFragment: 'setWithdrawalsActive',
    data: BytesLike
  ): Result
  decodeFunctionResult(
    functionFragment: 'transferOwnership',
    data: BytesLike
  ): Result
  decodeFunctionResult(
    functionFragment: 'withdrawalsActive',
    data: BytesLike
  ): Result

  events: {
    'AdminWithdraw(address,address[],uint256[][])': EventFragment
    'BridgeAddressUpdated(address)': EventFragment
    'Deposit(address,address[],uint256[][],address[],address)': EventFragment
    'DepositActiveStatus(bool)': EventFragment
    'OwnershipTransferred(address,address)': EventFragment
    'PalletAddressUpdated(address)': EventFragment
    'Withdraw(address,address[],uint256[][])': EventFragment
    'WithdrawalActiveStatus(bool)': EventFragment
  }

  getEvent(nameOrSignatureOrTopic: 'AdminWithdraw'): EventFragment
  getEvent(nameOrSignatureOrTopic: 'BridgeAddressUpdated'): EventFragment
  getEvent(nameOrSignatureOrTopic: 'Deposit'): EventFragment
  getEvent(nameOrSignatureOrTopic: 'DepositActiveStatus'): EventFragment
  getEvent(nameOrSignatureOrTopic: 'OwnershipTransferred'): EventFragment
  getEvent(nameOrSignatureOrTopic: 'PalletAddressUpdated'): EventFragment
  getEvent(nameOrSignatureOrTopic: 'Withdraw'): EventFragment
  getEvent(nameOrSignatureOrTopic: 'WithdrawalActiveStatus'): EventFragment
}

export interface AdminWithdrawEventObject {
  _address: string
  tokenAddresses: string[]
  tokenIds: BigNumber[][]
}
export type AdminWithdrawEvent = TypedEvent<
  [string, string[], BigNumber[][]],
  AdminWithdrawEventObject
>

export type AdminWithdrawEventFilter = TypedEventFilter<AdminWithdrawEvent>

export interface BridgeAddressUpdatedEventObject {
  bridge: string
}
export type BridgeAddressUpdatedEvent = TypedEvent<
  [string],
  BridgeAddressUpdatedEventObject
>

export type BridgeAddressUpdatedEventFilter =
  TypedEventFilter<BridgeAddressUpdatedEvent>

export interface DepositEventObject {
  _address: string
  tokenAddresses: string[]
  tokenIds: BigNumber[][]
  contractOwners: string[]
  destination: string
}
export type DepositEvent = TypedEvent<
  [string, string[], BigNumber[][], string[], string],
  DepositEventObject
>

export type DepositEventFilter = TypedEventFilter<DepositEvent>

export interface DepositActiveStatusEventObject {
  active: boolean
}
export type DepositActiveStatusEvent = TypedEvent<
  [boolean],
  DepositActiveStatusEventObject
>

export type DepositActiveStatusEventFilter =
  TypedEventFilter<DepositActiveStatusEvent>

export interface OwnershipTransferredEventObject {
  previousOwner: string
  newOwner: string
}
export type OwnershipTransferredEvent = TypedEvent<
  [string, string],
  OwnershipTransferredEventObject
>

export type OwnershipTransferredEventFilter =
  TypedEventFilter<OwnershipTransferredEvent>

export interface PalletAddressUpdatedEventObject {
  palletAddress: string
}
export type PalletAddressUpdatedEvent = TypedEvent<
  [string],
  PalletAddressUpdatedEventObject
>

export type PalletAddressUpdatedEventFilter =
  TypedEventFilter<PalletAddressUpdatedEvent>

export interface WithdrawEventObject {
  _address: string
  tokenAddresses: string[]
  tokenIds: BigNumber[][]
}
export type WithdrawEvent = TypedEvent<
  [string, string[], BigNumber[][]],
  WithdrawEventObject
>

export type WithdrawEventFilter = TypedEventFilter<WithdrawEvent>

export interface WithdrawalActiveStatusEventObject {
  active: boolean
}
export type WithdrawalActiveStatusEvent = TypedEvent<
  [boolean],
  WithdrawalActiveStatusEventObject
>

export type WithdrawalActiveStatusEventFilter =
  TypedEventFilter<WithdrawalActiveStatusEvent>

export interface Erc721Peg extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this
  attach(addressOrName: string): this
  deployed(): Promise<this>

  interface: Erc721PegInterface

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>
  listeners(eventName?: string): Array<Listener>
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this
  removeAllListeners(eventName?: string): this
  off: OnEvent<this>
  on: OnEvent<this>
  once: OnEvent<this>
  removeListener: OnEvent<this>

  functions: {
    adminEmergencyWithdraw(
      _tokenAddresses: PromiseOrValue<string>[],
      _tokenIds: PromiseOrValue<BigNumberish>[][],
      _recipient: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>

    bridge(overrides?: CallOverrides): Promise<[string]>

    deposit(
      _tokenAddresses: PromiseOrValue<string>[],
      _tokenIds: PromiseOrValue<BigNumberish>[][],
      _destination: PromiseOrValue<string>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>

    depositsActive(overrides?: CallOverrides): Promise<[boolean]>

    onERC721Received(
      arg0: PromiseOrValue<string>,
      arg1: PromiseOrValue<string>,
      arg2: PromiseOrValue<BigNumberish>,
      arg3: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>

    onMessageReceived(
      _source: PromiseOrValue<string>,
      _message: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>

    owner(overrides?: CallOverrides): Promise<[string]>

    palletAddress(overrides?: CallOverrides): Promise<[string]>

    renounceOwnership(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>

    setBridgeAddress(
      _bridge: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>

    setDepositsActive(
      _active: PromiseOrValue<boolean>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>

    setPalletAddress(
      _palletAddress: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>

    setWithdrawalsActive(
      _active: PromiseOrValue<boolean>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>

    transferOwnership(
      newOwner: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>

    withdrawalsActive(overrides?: CallOverrides): Promise<[boolean]>
  }

  adminEmergencyWithdraw(
    _tokenAddresses: PromiseOrValue<string>[],
    _tokenIds: PromiseOrValue<BigNumberish>[][],
    _recipient: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>

  bridge(overrides?: CallOverrides): Promise<string>

  deposit(
    _tokenAddresses: PromiseOrValue<string>[],
    _tokenIds: PromiseOrValue<BigNumberish>[][],
    _destination: PromiseOrValue<string>,
    overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>

  depositsActive(overrides?: CallOverrides): Promise<boolean>

  onERC721Received(
    arg0: PromiseOrValue<string>,
    arg1: PromiseOrValue<string>,
    arg2: PromiseOrValue<BigNumberish>,
    arg3: PromiseOrValue<BytesLike>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>

  onMessageReceived(
    _source: PromiseOrValue<string>,
    _message: PromiseOrValue<BytesLike>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>

  owner(overrides?: CallOverrides): Promise<string>

  palletAddress(overrides?: CallOverrides): Promise<string>

  renounceOwnership(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>

  setBridgeAddress(
    _bridge: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>

  setDepositsActive(
    _active: PromiseOrValue<boolean>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>

  setPalletAddress(
    _palletAddress: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>

  setWithdrawalsActive(
    _active: PromiseOrValue<boolean>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>

  transferOwnership(
    newOwner: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>

  withdrawalsActive(overrides?: CallOverrides): Promise<boolean>

  callStatic: {
    adminEmergencyWithdraw(
      _tokenAddresses: PromiseOrValue<string>[],
      _tokenIds: PromiseOrValue<BigNumberish>[][],
      _recipient: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>

    bridge(overrides?: CallOverrides): Promise<string>

    deposit(
      _tokenAddresses: PromiseOrValue<string>[],
      _tokenIds: PromiseOrValue<BigNumberish>[][],
      _destination: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>

    depositsActive(overrides?: CallOverrides): Promise<boolean>

    onERC721Received(
      arg0: PromiseOrValue<string>,
      arg1: PromiseOrValue<string>,
      arg2: PromiseOrValue<BigNumberish>,
      arg3: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<string>

    onMessageReceived(
      _source: PromiseOrValue<string>,
      _message: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<void>

    owner(overrides?: CallOverrides): Promise<string>

    palletAddress(overrides?: CallOverrides): Promise<string>

    renounceOwnership(overrides?: CallOverrides): Promise<void>

    setBridgeAddress(
      _bridge: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>

    setDepositsActive(
      _active: PromiseOrValue<boolean>,
      overrides?: CallOverrides
    ): Promise<void>

    setPalletAddress(
      _palletAddress: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>

    setWithdrawalsActive(
      _active: PromiseOrValue<boolean>,
      overrides?: CallOverrides
    ): Promise<void>

    transferOwnership(
      newOwner: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>

    withdrawalsActive(overrides?: CallOverrides): Promise<boolean>
  }

  filters: {
    'AdminWithdraw(address,address[],uint256[][])'(
      _address?: PromiseOrValue<string> | null,
      tokenAddresses?: PromiseOrValue<string>[] | null,
      tokenIds?: PromiseOrValue<BigNumberish>[][] | null
    ): AdminWithdrawEventFilter
    AdminWithdraw(
      _address?: PromiseOrValue<string> | null,
      tokenAddresses?: PromiseOrValue<string>[] | null,
      tokenIds?: PromiseOrValue<BigNumberish>[][] | null
    ): AdminWithdrawEventFilter

    'BridgeAddressUpdated(address)'(
      bridge?: PromiseOrValue<string> | null
    ): BridgeAddressUpdatedEventFilter
    BridgeAddressUpdated(
      bridge?: PromiseOrValue<string> | null
    ): BridgeAddressUpdatedEventFilter

    'Deposit(address,address[],uint256[][],address[],address)'(
      _address?: PromiseOrValue<string> | null,
      tokenAddresses?: PromiseOrValue<string>[] | null,
      tokenIds?: PromiseOrValue<BigNumberish>[][] | null,
      contractOwners?: null,
      destination?: null
    ): DepositEventFilter
    Deposit(
      _address?: PromiseOrValue<string> | null,
      tokenAddresses?: PromiseOrValue<string>[] | null,
      tokenIds?: PromiseOrValue<BigNumberish>[][] | null,
      contractOwners?: null,
      destination?: null
    ): DepositEventFilter

    'DepositActiveStatus(bool)'(
      active?: PromiseOrValue<boolean> | null
    ): DepositActiveStatusEventFilter
    DepositActiveStatus(
      active?: PromiseOrValue<boolean> | null
    ): DepositActiveStatusEventFilter

    'OwnershipTransferred(address,address)'(
      previousOwner?: PromiseOrValue<string> | null,
      newOwner?: PromiseOrValue<string> | null
    ): OwnershipTransferredEventFilter
    OwnershipTransferred(
      previousOwner?: PromiseOrValue<string> | null,
      newOwner?: PromiseOrValue<string> | null
    ): OwnershipTransferredEventFilter

    'PalletAddressUpdated(address)'(
      palletAddress?: PromiseOrValue<string> | null
    ): PalletAddressUpdatedEventFilter
    PalletAddressUpdated(
      palletAddress?: PromiseOrValue<string> | null
    ): PalletAddressUpdatedEventFilter

    'Withdraw(address,address[],uint256[][])'(
      _address?: PromiseOrValue<string> | null,
      tokenAddresses?: PromiseOrValue<string>[] | null,
      tokenIds?: PromiseOrValue<BigNumberish>[][] | null
    ): WithdrawEventFilter
    Withdraw(
      _address?: PromiseOrValue<string> | null,
      tokenAddresses?: PromiseOrValue<string>[] | null,
      tokenIds?: PromiseOrValue<BigNumberish>[][] | null
    ): WithdrawEventFilter

    'WithdrawalActiveStatus(bool)'(
      active?: PromiseOrValue<boolean> | null
    ): WithdrawalActiveStatusEventFilter
    WithdrawalActiveStatus(
      active?: PromiseOrValue<boolean> | null
    ): WithdrawalActiveStatusEventFilter
  }

  estimateGas: {
    adminEmergencyWithdraw(
      _tokenAddresses: PromiseOrValue<string>[],
      _tokenIds: PromiseOrValue<BigNumberish>[][],
      _recipient: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>

    bridge(overrides?: CallOverrides): Promise<BigNumber>

    deposit(
      _tokenAddresses: PromiseOrValue<string>[],
      _tokenIds: PromiseOrValue<BigNumberish>[][],
      _destination: PromiseOrValue<string>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>

    depositsActive(overrides?: CallOverrides): Promise<BigNumber>

    onERC721Received(
      arg0: PromiseOrValue<string>,
      arg1: PromiseOrValue<string>,
      arg2: PromiseOrValue<BigNumberish>,
      arg3: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>

    onMessageReceived(
      _source: PromiseOrValue<string>,
      _message: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>

    owner(overrides?: CallOverrides): Promise<BigNumber>

    palletAddress(overrides?: CallOverrides): Promise<BigNumber>

    renounceOwnership(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>

    setBridgeAddress(
      _bridge: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>

    setDepositsActive(
      _active: PromiseOrValue<boolean>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>

    setPalletAddress(
      _palletAddress: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>

    setWithdrawalsActive(
      _active: PromiseOrValue<boolean>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>

    transferOwnership(
      newOwner: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>

    withdrawalsActive(overrides?: CallOverrides): Promise<BigNumber>
  }

  populateTransaction: {
    adminEmergencyWithdraw(
      _tokenAddresses: PromiseOrValue<string>[],
      _tokenIds: PromiseOrValue<BigNumberish>[][],
      _recipient: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>

    bridge(overrides?: CallOverrides): Promise<PopulatedTransaction>

    deposit(
      _tokenAddresses: PromiseOrValue<string>[],
      _tokenIds: PromiseOrValue<BigNumberish>[][],
      _destination: PromiseOrValue<string>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>

    depositsActive(overrides?: CallOverrides): Promise<PopulatedTransaction>

    onERC721Received(
      arg0: PromiseOrValue<string>,
      arg1: PromiseOrValue<string>,
      arg2: PromiseOrValue<BigNumberish>,
      arg3: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>

    onMessageReceived(
      _source: PromiseOrValue<string>,
      _message: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>

    owner(overrides?: CallOverrides): Promise<PopulatedTransaction>

    palletAddress(overrides?: CallOverrides): Promise<PopulatedTransaction>

    renounceOwnership(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>

    setBridgeAddress(
      _bridge: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>

    setDepositsActive(
      _active: PromiseOrValue<boolean>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>

    setPalletAddress(
      _palletAddress: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>

    setWithdrawalsActive(
      _active: PromiseOrValue<boolean>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>

    transferOwnership(
      newOwner: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>

    withdrawalsActive(overrides?: CallOverrides): Promise<PopulatedTransaction>
  }
}
