/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PayableOverrides,
  PopulatedTransaction,
  Signer,
  utils,
} from 'ethers'
import type {
  FunctionFragment,
  Result,
  EventFragment,
} from '@ethersproject/abi'
import type { Listener, Provider } from '@ethersproject/providers'
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from './common'

export interface FuturePassInterface extends utils.Interface {
  functions: {
    'RENOUNCE_OWNERSHIP_CONFIRMATION_DELAY()': FunctionFragment
    'RENOUNCE_OWNERSHIP_CONFIRMATION_PERIOD()': FunctionFragment
    'acceptOwnership()': FunctionFragment
    'execute(uint256[],address[],uint256[],bytes[])': FunctionFragment
    'execute(uint256,address,uint256,bytes)': FunctionFragment
    'getData(bytes32[])': FunctionFragment
    'getData(bytes32)': FunctionFragment
    'initialize(address,bytes32,bytes)': FunctionFragment
    'isValidSignature(bytes32,bytes)': FunctionFragment
    'onERC1155BatchReceived(address,address,uint256[],uint256[],bytes)': FunctionFragment
    'onERC1155Received(address,address,uint256,uint256,bytes)': FunctionFragment
    'onERC721Received(address,address,uint256,bytes)': FunctionFragment
    'owner()': FunctionFragment
    'pendingOwner()': FunctionFragment
    'renounceOwnership()': FunctionFragment
    'setData(bytes32[],bytes[])': FunctionFragment
    'setData(bytes32,bytes)': FunctionFragment
    'supportsInterface(bytes4)': FunctionFragment
    'transferOwnership(address)': FunctionFragment
    'universalReceiver(bytes32,bytes)': FunctionFragment
  }

  getFunction(
    nameOrSignatureOrTopic:
      | 'RENOUNCE_OWNERSHIP_CONFIRMATION_DELAY'
      | 'RENOUNCE_OWNERSHIP_CONFIRMATION_PERIOD'
      | 'acceptOwnership'
      | 'execute(uint256[],address[],uint256[],bytes[])'
      | 'execute(uint256,address,uint256,bytes)'
      | 'getData(bytes32[])'
      | 'getData(bytes32)'
      | 'initialize'
      | 'isValidSignature'
      | 'onERC1155BatchReceived'
      | 'onERC1155Received'
      | 'onERC721Received'
      | 'owner'
      | 'pendingOwner'
      | 'renounceOwnership'
      | 'setData(bytes32[],bytes[])'
      | 'setData(bytes32,bytes)'
      | 'supportsInterface'
      | 'transferOwnership'
      | 'universalReceiver'
  ): FunctionFragment

  encodeFunctionData(
    functionFragment: 'RENOUNCE_OWNERSHIP_CONFIRMATION_DELAY',
    values?: undefined
  ): string
  encodeFunctionData(
    functionFragment: 'RENOUNCE_OWNERSHIP_CONFIRMATION_PERIOD',
    values?: undefined
  ): string
  encodeFunctionData(
    functionFragment: 'acceptOwnership',
    values?: undefined
  ): string
  encodeFunctionData(
    functionFragment: 'execute(uint256[],address[],uint256[],bytes[])',
    values: [
      PromiseOrValue<BigNumberish>[],
      PromiseOrValue<string>[],
      PromiseOrValue<BigNumberish>[],
      PromiseOrValue<BytesLike>[]
    ]
  ): string
  encodeFunctionData(
    functionFragment: 'execute(uint256,address,uint256,bytes)',
    values: [
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BytesLike>
    ]
  ): string
  encodeFunctionData(
    functionFragment: 'getData(bytes32[])',
    values: [PromiseOrValue<BytesLike>[]]
  ): string
  encodeFunctionData(
    functionFragment: 'getData(bytes32)',
    values: [PromiseOrValue<BytesLike>]
  ): string
  encodeFunctionData(
    functionFragment: 'initialize',
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<BytesLike>,
      PromiseOrValue<BytesLike>
    ]
  ): string
  encodeFunctionData(
    functionFragment: 'isValidSignature',
    values: [PromiseOrValue<BytesLike>, PromiseOrValue<BytesLike>]
  ): string
  encodeFunctionData(
    functionFragment: 'onERC1155BatchReceived',
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>[],
      PromiseOrValue<BigNumberish>[],
      PromiseOrValue<BytesLike>
    ]
  ): string
  encodeFunctionData(
    functionFragment: 'onERC1155Received',
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BytesLike>
    ]
  ): string
  encodeFunctionData(
    functionFragment: 'onERC721Received',
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BytesLike>
    ]
  ): string
  encodeFunctionData(functionFragment: 'owner', values?: undefined): string
  encodeFunctionData(
    functionFragment: 'pendingOwner',
    values?: undefined
  ): string
  encodeFunctionData(
    functionFragment: 'renounceOwnership',
    values?: undefined
  ): string
  encodeFunctionData(
    functionFragment: 'setData(bytes32[],bytes[])',
    values: [PromiseOrValue<BytesLike>[], PromiseOrValue<BytesLike>[]]
  ): string
  encodeFunctionData(
    functionFragment: 'setData(bytes32,bytes)',
    values: [PromiseOrValue<BytesLike>, PromiseOrValue<BytesLike>]
  ): string
  encodeFunctionData(
    functionFragment: 'supportsInterface',
    values: [PromiseOrValue<BytesLike>]
  ): string
  encodeFunctionData(
    functionFragment: 'transferOwnership',
    values: [PromiseOrValue<string>]
  ): string
  encodeFunctionData(
    functionFragment: 'universalReceiver',
    values: [PromiseOrValue<BytesLike>, PromiseOrValue<BytesLike>]
  ): string

  decodeFunctionResult(
    functionFragment: 'RENOUNCE_OWNERSHIP_CONFIRMATION_DELAY',
    data: BytesLike
  ): Result
  decodeFunctionResult(
    functionFragment: 'RENOUNCE_OWNERSHIP_CONFIRMATION_PERIOD',
    data: BytesLike
  ): Result
  decodeFunctionResult(
    functionFragment: 'acceptOwnership',
    data: BytesLike
  ): Result
  decodeFunctionResult(
    functionFragment: 'execute(uint256[],address[],uint256[],bytes[])',
    data: BytesLike
  ): Result
  decodeFunctionResult(
    functionFragment: 'execute(uint256,address,uint256,bytes)',
    data: BytesLike
  ): Result
  decodeFunctionResult(
    functionFragment: 'getData(bytes32[])',
    data: BytesLike
  ): Result
  decodeFunctionResult(
    functionFragment: 'getData(bytes32)',
    data: BytesLike
  ): Result
  decodeFunctionResult(functionFragment: 'initialize', data: BytesLike): Result
  decodeFunctionResult(
    functionFragment: 'isValidSignature',
    data: BytesLike
  ): Result
  decodeFunctionResult(
    functionFragment: 'onERC1155BatchReceived',
    data: BytesLike
  ): Result
  decodeFunctionResult(
    functionFragment: 'onERC1155Received',
    data: BytesLike
  ): Result
  decodeFunctionResult(
    functionFragment: 'onERC721Received',
    data: BytesLike
  ): Result
  decodeFunctionResult(functionFragment: 'owner', data: BytesLike): Result
  decodeFunctionResult(
    functionFragment: 'pendingOwner',
    data: BytesLike
  ): Result
  decodeFunctionResult(
    functionFragment: 'renounceOwnership',
    data: BytesLike
  ): Result
  decodeFunctionResult(
    functionFragment: 'setData(bytes32[],bytes[])',
    data: BytesLike
  ): Result
  decodeFunctionResult(
    functionFragment: 'setData(bytes32,bytes)',
    data: BytesLike
  ): Result
  decodeFunctionResult(
    functionFragment: 'supportsInterface',
    data: BytesLike
  ): Result
  decodeFunctionResult(
    functionFragment: 'transferOwnership',
    data: BytesLike
  ): Result
  decodeFunctionResult(
    functionFragment: 'universalReceiver',
    data: BytesLike
  ): Result

  events: {
    'ContractCreated(uint256,address,uint256,bytes32)': EventFragment
    'DataChanged(bytes32,bytes)': EventFragment
    'Executed(uint256,address,uint256,bytes4)': EventFragment
    'Initialized(uint8)': EventFragment
    'OwnershipRenounced()': EventFragment
    'OwnershipTransferStarted(address,address)': EventFragment
    'OwnershipTransferred(address,address)': EventFragment
    'RenounceOwnershipStarted()': EventFragment
    'UniversalReceiver(address,uint256,bytes32,bytes,bytes)': EventFragment
    'ValueReceived(address,uint256)': EventFragment
  }

  getEvent(nameOrSignatureOrTopic: 'ContractCreated'): EventFragment
  getEvent(nameOrSignatureOrTopic: 'DataChanged'): EventFragment
  getEvent(nameOrSignatureOrTopic: 'Executed'): EventFragment
  getEvent(nameOrSignatureOrTopic: 'Initialized'): EventFragment
  getEvent(nameOrSignatureOrTopic: 'OwnershipRenounced'): EventFragment
  getEvent(nameOrSignatureOrTopic: 'OwnershipTransferStarted'): EventFragment
  getEvent(nameOrSignatureOrTopic: 'OwnershipTransferred'): EventFragment
  getEvent(nameOrSignatureOrTopic: 'RenounceOwnershipStarted'): EventFragment
  getEvent(nameOrSignatureOrTopic: 'UniversalReceiver'): EventFragment
  getEvent(nameOrSignatureOrTopic: 'ValueReceived'): EventFragment
}

export interface ContractCreatedEventObject {
  operationType: BigNumber
  contractAddress: string
  value: BigNumber
  salt: string
}
export type ContractCreatedEvent = TypedEvent<
  [BigNumber, string, BigNumber, string],
  ContractCreatedEventObject
>

export type ContractCreatedEventFilter = TypedEventFilter<ContractCreatedEvent>

export interface DataChangedEventObject {
  dataKey: string
  dataValue: string
}
export type DataChangedEvent = TypedEvent<
  [string, string],
  DataChangedEventObject
>

export type DataChangedEventFilter = TypedEventFilter<DataChangedEvent>

export interface ExecutedEventObject {
  operationType: BigNumber
  target: string
  value: BigNumber
  selector: string
}
export type ExecutedEvent = TypedEvent<
  [BigNumber, string, BigNumber, string],
  ExecutedEventObject
>

export type ExecutedEventFilter = TypedEventFilter<ExecutedEvent>

export interface InitializedEventObject {
  version: number
}
export type InitializedEvent = TypedEvent<[number], InitializedEventObject>

export type InitializedEventFilter = TypedEventFilter<InitializedEvent>

export interface OwnershipRenouncedEventObject {}
export type OwnershipRenouncedEvent = TypedEvent<
  [],
  OwnershipRenouncedEventObject
>

export type OwnershipRenouncedEventFilter =
  TypedEventFilter<OwnershipRenouncedEvent>

export interface OwnershipTransferStartedEventObject {
  previousOwner: string
  newOwner: string
}
export type OwnershipTransferStartedEvent = TypedEvent<
  [string, string],
  OwnershipTransferStartedEventObject
>

export type OwnershipTransferStartedEventFilter =
  TypedEventFilter<OwnershipTransferStartedEvent>

export interface OwnershipTransferredEventObject {
  previousOwner: string
  newOwner: string
}
export type OwnershipTransferredEvent = TypedEvent<
  [string, string],
  OwnershipTransferredEventObject
>

export type OwnershipTransferredEventFilter =
  TypedEventFilter<OwnershipTransferredEvent>

export interface RenounceOwnershipStartedEventObject {}
export type RenounceOwnershipStartedEvent = TypedEvent<
  [],
  RenounceOwnershipStartedEventObject
>

export type RenounceOwnershipStartedEventFilter =
  TypedEventFilter<RenounceOwnershipStartedEvent>

export interface UniversalReceiverEventObject {
  from: string
  value: BigNumber
  typeId: string
  receivedData: string
  returnedValue: string
}
export type UniversalReceiverEvent = TypedEvent<
  [string, BigNumber, string, string, string],
  UniversalReceiverEventObject
>

export type UniversalReceiverEventFilter =
  TypedEventFilter<UniversalReceiverEvent>

export interface ValueReceivedEventObject {
  sender: string
  value: BigNumber
}
export type ValueReceivedEvent = TypedEvent<
  [string, BigNumber],
  ValueReceivedEventObject
>

export type ValueReceivedEventFilter = TypedEventFilter<ValueReceivedEvent>

export interface FuturePass extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this
  attach(addressOrName: string): this
  deployed(): Promise<this>

  interface: FuturePassInterface

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>
  listeners(eventName?: string): Array<Listener>
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this
  removeAllListeners(eventName?: string): this
  off: OnEvent<this>
  on: OnEvent<this>
  once: OnEvent<this>
  removeListener: OnEvent<this>

  functions: {
    RENOUNCE_OWNERSHIP_CONFIRMATION_DELAY(
      overrides?: CallOverrides
    ): Promise<[BigNumber]>

    RENOUNCE_OWNERSHIP_CONFIRMATION_PERIOD(
      overrides?: CallOverrides
    ): Promise<[BigNumber]>

    acceptOwnership(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>

    'execute(uint256[],address[],uint256[],bytes[])'(
      operationsType: PromiseOrValue<BigNumberish>[],
      targets: PromiseOrValue<string>[],
      values: PromiseOrValue<BigNumberish>[],
      datas: PromiseOrValue<BytesLike>[],
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>

    'execute(uint256,address,uint256,bytes)'(
      operationType: PromiseOrValue<BigNumberish>,
      target: PromiseOrValue<string>,
      value: PromiseOrValue<BigNumberish>,
      data: PromiseOrValue<BytesLike>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>

    'getData(bytes32[])'(
      dataKeys: PromiseOrValue<BytesLike>[],
      overrides?: CallOverrides
    ): Promise<[string[]] & { dataValues: string[] }>

    'getData(bytes32)'(
      dataKey: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<[string] & { dataValue: string }>

    initialize(
      newOwner: PromiseOrValue<string>,
      dataKey: PromiseOrValue<BytesLike>,
      dataValue: PromiseOrValue<BytesLike>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>

    isValidSignature(
      dataHash: PromiseOrValue<BytesLike>,
      signature: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<[string] & { magicValue: string }>

    onERC1155BatchReceived(
      arg0: PromiseOrValue<string>,
      arg1: PromiseOrValue<string>,
      arg2: PromiseOrValue<BigNumberish>[],
      arg3: PromiseOrValue<BigNumberish>[],
      arg4: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>

    onERC1155Received(
      arg0: PromiseOrValue<string>,
      arg1: PromiseOrValue<string>,
      arg2: PromiseOrValue<BigNumberish>,
      arg3: PromiseOrValue<BigNumberish>,
      arg4: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>

    onERC721Received(
      arg0: PromiseOrValue<string>,
      arg1: PromiseOrValue<string>,
      arg2: PromiseOrValue<BigNumberish>,
      arg3: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>

    owner(overrides?: CallOverrides): Promise<[string]>

    pendingOwner(overrides?: CallOverrides): Promise<[string]>

    renounceOwnership(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>

    'setData(bytes32[],bytes[])'(
      dataKeys: PromiseOrValue<BytesLike>[],
      dataValues: PromiseOrValue<BytesLike>[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>

    'setData(bytes32,bytes)'(
      dataKey: PromiseOrValue<BytesLike>,
      dataValue: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>

    supportsInterface(
      interfaceId: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<[boolean]>

    transferOwnership(
      _newOwner: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>

    universalReceiver(
      typeId: PromiseOrValue<BytesLike>,
      receivedData: PromiseOrValue<BytesLike>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>
  }

  RENOUNCE_OWNERSHIP_CONFIRMATION_DELAY(
    overrides?: CallOverrides
  ): Promise<BigNumber>

  RENOUNCE_OWNERSHIP_CONFIRMATION_PERIOD(
    overrides?: CallOverrides
  ): Promise<BigNumber>

  acceptOwnership(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>

  'execute(uint256[],address[],uint256[],bytes[])'(
    operationsType: PromiseOrValue<BigNumberish>[],
    targets: PromiseOrValue<string>[],
    values: PromiseOrValue<BigNumberish>[],
    datas: PromiseOrValue<BytesLike>[],
    overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>

  'execute(uint256,address,uint256,bytes)'(
    operationType: PromiseOrValue<BigNumberish>,
    target: PromiseOrValue<string>,
    value: PromiseOrValue<BigNumberish>,
    data: PromiseOrValue<BytesLike>,
    overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>

  'getData(bytes32[])'(
    dataKeys: PromiseOrValue<BytesLike>[],
    overrides?: CallOverrides
  ): Promise<string[]>

  'getData(bytes32)'(
    dataKey: PromiseOrValue<BytesLike>,
    overrides?: CallOverrides
  ): Promise<string>

  initialize(
    newOwner: PromiseOrValue<string>,
    dataKey: PromiseOrValue<BytesLike>,
    dataValue: PromiseOrValue<BytesLike>,
    overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>

  isValidSignature(
    dataHash: PromiseOrValue<BytesLike>,
    signature: PromiseOrValue<BytesLike>,
    overrides?: CallOverrides
  ): Promise<string>

  onERC1155BatchReceived(
    arg0: PromiseOrValue<string>,
    arg1: PromiseOrValue<string>,
    arg2: PromiseOrValue<BigNumberish>[],
    arg3: PromiseOrValue<BigNumberish>[],
    arg4: PromiseOrValue<BytesLike>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>

  onERC1155Received(
    arg0: PromiseOrValue<string>,
    arg1: PromiseOrValue<string>,
    arg2: PromiseOrValue<BigNumberish>,
    arg3: PromiseOrValue<BigNumberish>,
    arg4: PromiseOrValue<BytesLike>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>

  onERC721Received(
    arg0: PromiseOrValue<string>,
    arg1: PromiseOrValue<string>,
    arg2: PromiseOrValue<BigNumberish>,
    arg3: PromiseOrValue<BytesLike>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>

  owner(overrides?: CallOverrides): Promise<string>

  pendingOwner(overrides?: CallOverrides): Promise<string>

  renounceOwnership(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>

  'setData(bytes32[],bytes[])'(
    dataKeys: PromiseOrValue<BytesLike>[],
    dataValues: PromiseOrValue<BytesLike>[],
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>

  'setData(bytes32,bytes)'(
    dataKey: PromiseOrValue<BytesLike>,
    dataValue: PromiseOrValue<BytesLike>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>

  supportsInterface(
    interfaceId: PromiseOrValue<BytesLike>,
    overrides?: CallOverrides
  ): Promise<boolean>

  transferOwnership(
    _newOwner: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>

  universalReceiver(
    typeId: PromiseOrValue<BytesLike>,
    receivedData: PromiseOrValue<BytesLike>,
    overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>

  callStatic: {
    RENOUNCE_OWNERSHIP_CONFIRMATION_DELAY(
      overrides?: CallOverrides
    ): Promise<BigNumber>

    RENOUNCE_OWNERSHIP_CONFIRMATION_PERIOD(
      overrides?: CallOverrides
    ): Promise<BigNumber>

    acceptOwnership(overrides?: CallOverrides): Promise<void>

    'execute(uint256[],address[],uint256[],bytes[])'(
      operationsType: PromiseOrValue<BigNumberish>[],
      targets: PromiseOrValue<string>[],
      values: PromiseOrValue<BigNumberish>[],
      datas: PromiseOrValue<BytesLike>[],
      overrides?: CallOverrides
    ): Promise<string[]>

    'execute(uint256,address,uint256,bytes)'(
      operationType: PromiseOrValue<BigNumberish>,
      target: PromiseOrValue<string>,
      value: PromiseOrValue<BigNumberish>,
      data: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<string>

    'getData(bytes32[])'(
      dataKeys: PromiseOrValue<BytesLike>[],
      overrides?: CallOverrides
    ): Promise<string[]>

    'getData(bytes32)'(
      dataKey: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<string>

    initialize(
      newOwner: PromiseOrValue<string>,
      dataKey: PromiseOrValue<BytesLike>,
      dataValue: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<void>

    isValidSignature(
      dataHash: PromiseOrValue<BytesLike>,
      signature: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<string>

    onERC1155BatchReceived(
      arg0: PromiseOrValue<string>,
      arg1: PromiseOrValue<string>,
      arg2: PromiseOrValue<BigNumberish>[],
      arg3: PromiseOrValue<BigNumberish>[],
      arg4: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<string>

    onERC1155Received(
      arg0: PromiseOrValue<string>,
      arg1: PromiseOrValue<string>,
      arg2: PromiseOrValue<BigNumberish>,
      arg3: PromiseOrValue<BigNumberish>,
      arg4: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<string>

    onERC721Received(
      arg0: PromiseOrValue<string>,
      arg1: PromiseOrValue<string>,
      arg2: PromiseOrValue<BigNumberish>,
      arg3: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<string>

    owner(overrides?: CallOverrides): Promise<string>

    pendingOwner(overrides?: CallOverrides): Promise<string>

    renounceOwnership(overrides?: CallOverrides): Promise<void>

    'setData(bytes32[],bytes[])'(
      dataKeys: PromiseOrValue<BytesLike>[],
      dataValues: PromiseOrValue<BytesLike>[],
      overrides?: CallOverrides
    ): Promise<void>

    'setData(bytes32,bytes)'(
      dataKey: PromiseOrValue<BytesLike>,
      dataValue: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<void>

    supportsInterface(
      interfaceId: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<boolean>

    transferOwnership(
      _newOwner: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>

    universalReceiver(
      typeId: PromiseOrValue<BytesLike>,
      receivedData: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<string>
  }

  filters: {
    'ContractCreated(uint256,address,uint256,bytes32)'(
      operationType?: PromiseOrValue<BigNumberish> | null,
      contractAddress?: PromiseOrValue<string> | null,
      value?: PromiseOrValue<BigNumberish> | null,
      salt?: null
    ): ContractCreatedEventFilter
    ContractCreated(
      operationType?: PromiseOrValue<BigNumberish> | null,
      contractAddress?: PromiseOrValue<string> | null,
      value?: PromiseOrValue<BigNumberish> | null,
      salt?: null
    ): ContractCreatedEventFilter

    'DataChanged(bytes32,bytes)'(
      dataKey?: PromiseOrValue<BytesLike> | null,
      dataValue?: null
    ): DataChangedEventFilter
    DataChanged(
      dataKey?: PromiseOrValue<BytesLike> | null,
      dataValue?: null
    ): DataChangedEventFilter

    'Executed(uint256,address,uint256,bytes4)'(
      operationType?: PromiseOrValue<BigNumberish> | null,
      target?: PromiseOrValue<string> | null,
      value?: PromiseOrValue<BigNumberish> | null,
      selector?: null
    ): ExecutedEventFilter
    Executed(
      operationType?: PromiseOrValue<BigNumberish> | null,
      target?: PromiseOrValue<string> | null,
      value?: PromiseOrValue<BigNumberish> | null,
      selector?: null
    ): ExecutedEventFilter

    'Initialized(uint8)'(version?: null): InitializedEventFilter
    Initialized(version?: null): InitializedEventFilter

    'OwnershipRenounced()'(): OwnershipRenouncedEventFilter
    OwnershipRenounced(): OwnershipRenouncedEventFilter

    'OwnershipTransferStarted(address,address)'(
      previousOwner?: PromiseOrValue<string> | null,
      newOwner?: PromiseOrValue<string> | null
    ): OwnershipTransferStartedEventFilter
    OwnershipTransferStarted(
      previousOwner?: PromiseOrValue<string> | null,
      newOwner?: PromiseOrValue<string> | null
    ): OwnershipTransferStartedEventFilter

    'OwnershipTransferred(address,address)'(
      previousOwner?: PromiseOrValue<string> | null,
      newOwner?: PromiseOrValue<string> | null
    ): OwnershipTransferredEventFilter
    OwnershipTransferred(
      previousOwner?: PromiseOrValue<string> | null,
      newOwner?: PromiseOrValue<string> | null
    ): OwnershipTransferredEventFilter

    'RenounceOwnershipStarted()'(): RenounceOwnershipStartedEventFilter
    RenounceOwnershipStarted(): RenounceOwnershipStartedEventFilter

    'UniversalReceiver(address,uint256,bytes32,bytes,bytes)'(
      from?: PromiseOrValue<string> | null,
      value?: PromiseOrValue<BigNumberish> | null,
      typeId?: PromiseOrValue<BytesLike> | null,
      receivedData?: null,
      returnedValue?: null
    ): UniversalReceiverEventFilter
    UniversalReceiver(
      from?: PromiseOrValue<string> | null,
      value?: PromiseOrValue<BigNumberish> | null,
      typeId?: PromiseOrValue<BytesLike> | null,
      receivedData?: null,
      returnedValue?: null
    ): UniversalReceiverEventFilter

    'ValueReceived(address,uint256)'(
      sender?: PromiseOrValue<string> | null,
      value?: PromiseOrValue<BigNumberish> | null
    ): ValueReceivedEventFilter
    ValueReceived(
      sender?: PromiseOrValue<string> | null,
      value?: PromiseOrValue<BigNumberish> | null
    ): ValueReceivedEventFilter
  }

  estimateGas: {
    RENOUNCE_OWNERSHIP_CONFIRMATION_DELAY(
      overrides?: CallOverrides
    ): Promise<BigNumber>

    RENOUNCE_OWNERSHIP_CONFIRMATION_PERIOD(
      overrides?: CallOverrides
    ): Promise<BigNumber>

    acceptOwnership(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>

    'execute(uint256[],address[],uint256[],bytes[])'(
      operationsType: PromiseOrValue<BigNumberish>[],
      targets: PromiseOrValue<string>[],
      values: PromiseOrValue<BigNumberish>[],
      datas: PromiseOrValue<BytesLike>[],
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>

    'execute(uint256,address,uint256,bytes)'(
      operationType: PromiseOrValue<BigNumberish>,
      target: PromiseOrValue<string>,
      value: PromiseOrValue<BigNumberish>,
      data: PromiseOrValue<BytesLike>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>

    'getData(bytes32[])'(
      dataKeys: PromiseOrValue<BytesLike>[],
      overrides?: CallOverrides
    ): Promise<BigNumber>

    'getData(bytes32)'(
      dataKey: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<BigNumber>

    initialize(
      newOwner: PromiseOrValue<string>,
      dataKey: PromiseOrValue<BytesLike>,
      dataValue: PromiseOrValue<BytesLike>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>

    isValidSignature(
      dataHash: PromiseOrValue<BytesLike>,
      signature: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<BigNumber>

    onERC1155BatchReceived(
      arg0: PromiseOrValue<string>,
      arg1: PromiseOrValue<string>,
      arg2: PromiseOrValue<BigNumberish>[],
      arg3: PromiseOrValue<BigNumberish>[],
      arg4: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>

    onERC1155Received(
      arg0: PromiseOrValue<string>,
      arg1: PromiseOrValue<string>,
      arg2: PromiseOrValue<BigNumberish>,
      arg3: PromiseOrValue<BigNumberish>,
      arg4: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>

    onERC721Received(
      arg0: PromiseOrValue<string>,
      arg1: PromiseOrValue<string>,
      arg2: PromiseOrValue<BigNumberish>,
      arg3: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>

    owner(overrides?: CallOverrides): Promise<BigNumber>

    pendingOwner(overrides?: CallOverrides): Promise<BigNumber>

    renounceOwnership(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>

    'setData(bytes32[],bytes[])'(
      dataKeys: PromiseOrValue<BytesLike>[],
      dataValues: PromiseOrValue<BytesLike>[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>

    'setData(bytes32,bytes)'(
      dataKey: PromiseOrValue<BytesLike>,
      dataValue: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>

    supportsInterface(
      interfaceId: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<BigNumber>

    transferOwnership(
      _newOwner: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>

    universalReceiver(
      typeId: PromiseOrValue<BytesLike>,
      receivedData: PromiseOrValue<BytesLike>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>
  }

  populateTransaction: {
    RENOUNCE_OWNERSHIP_CONFIRMATION_DELAY(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>

    RENOUNCE_OWNERSHIP_CONFIRMATION_PERIOD(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>

    acceptOwnership(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>

    'execute(uint256[],address[],uint256[],bytes[])'(
      operationsType: PromiseOrValue<BigNumberish>[],
      targets: PromiseOrValue<string>[],
      values: PromiseOrValue<BigNumberish>[],
      datas: PromiseOrValue<BytesLike>[],
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>

    'execute(uint256,address,uint256,bytes)'(
      operationType: PromiseOrValue<BigNumberish>,
      target: PromiseOrValue<string>,
      value: PromiseOrValue<BigNumberish>,
      data: PromiseOrValue<BytesLike>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>

    'getData(bytes32[])'(
      dataKeys: PromiseOrValue<BytesLike>[],
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>

    'getData(bytes32)'(
      dataKey: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>

    initialize(
      newOwner: PromiseOrValue<string>,
      dataKey: PromiseOrValue<BytesLike>,
      dataValue: PromiseOrValue<BytesLike>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>

    isValidSignature(
      dataHash: PromiseOrValue<BytesLike>,
      signature: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>

    onERC1155BatchReceived(
      arg0: PromiseOrValue<string>,
      arg1: PromiseOrValue<string>,
      arg2: PromiseOrValue<BigNumberish>[],
      arg3: PromiseOrValue<BigNumberish>[],
      arg4: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>

    onERC1155Received(
      arg0: PromiseOrValue<string>,
      arg1: PromiseOrValue<string>,
      arg2: PromiseOrValue<BigNumberish>,
      arg3: PromiseOrValue<BigNumberish>,
      arg4: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>

    onERC721Received(
      arg0: PromiseOrValue<string>,
      arg1: PromiseOrValue<string>,
      arg2: PromiseOrValue<BigNumberish>,
      arg3: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>

    owner(overrides?: CallOverrides): Promise<PopulatedTransaction>

    pendingOwner(overrides?: CallOverrides): Promise<PopulatedTransaction>

    renounceOwnership(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>

    'setData(bytes32[],bytes[])'(
      dataKeys: PromiseOrValue<BytesLike>[],
      dataValues: PromiseOrValue<BytesLike>[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>

    'setData(bytes32,bytes)'(
      dataKey: PromiseOrValue<BytesLike>,
      dataValue: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>

    supportsInterface(
      interfaceId: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>

    transferOwnership(
      _newOwner: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>

    universalReceiver(
      typeId: PromiseOrValue<BytesLike>,
      receivedData: PromiseOrValue<BytesLike>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>
  }
}
