/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from 'ethers'
import type {
  FunctionFragment,
  Result,
  EventFragment,
} from '@ethersproject/abi'
import type { Listener, Provider } from '@ethersproject/providers'
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from './common'

export interface NativeFuturePassIdentityRegistryInterface
  extends utils.Interface {
  functions: {
    'futurepassOf(address)': FunctionFragment
    'create(address)': FunctionFragment
  }

  getFunction(
    nameOrSignatureOrTopic: 'futurepassOf' | 'create'
  ): FunctionFragment

  encodeFunctionData(
    functionFragment: 'futurepassOf',
    values: [PromiseOrValue<string>]
  ): string
  encodeFunctionData(
    functionFragment: 'create',
    values: [PromiseOrValue<string>]
  ): string

  decodeFunctionResult(
    functionFragment: 'futurepassOf',
    data: BytesLike
  ): Result
  decodeFunctionResult(functionFragment: 'create', data: BytesLike): Result

  events: {
    'FuturepassCreated(address,address)': EventFragment
  }

  getEvent(nameOrSignatureOrTopic: 'FuturepassCreated'): EventFragment
}

export interface FuturepassCreatedEventObject {
  futurepass: string
  owner: string
}
export type FuturepassCreatedEvent = TypedEvent<
  [string, string],
  FuturepassCreatedEventObject
>

export type FuturepassCreatedEventFilter =
  TypedEventFilter<FuturepassCreatedEvent>

export interface NativeFuturePassIdentityRegistry extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this
  attach(addressOrName: string): this
  deployed(): Promise<this>

  interface: NativeFuturePassIdentityRegistryInterface

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>
  listeners(eventName?: string): Array<Listener>
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this
  removeAllListeners(eventName?: string): this
  off: OnEvent<this>
  on: OnEvent<this>
  once: OnEvent<this>
  removeListener: OnEvent<this>

  functions: {
    futurepassOf(
      owner: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<[string]>

    create(
      owner: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>
  }

  futurepassOf(
    owner: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<string>

  create(
    owner: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>

  callStatic: {
    futurepassOf(
      owner: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<string>

    create(
      owner: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<string>
  }

  filters: {
    'FuturepassCreated(address,address)'(
      futurepass?: PromiseOrValue<string> | null,
      owner?: PromiseOrValue<string> | null
    ): FuturepassCreatedEventFilter
    FuturepassCreated(
      futurepass?: PromiseOrValue<string> | null,
      owner?: PromiseOrValue<string> | null
    ): FuturepassCreatedEventFilter
  }

  estimateGas: {
    futurepassOf(
      owner: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>

    create(
      owner: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>
  }

  populateTransaction: {
    futurepassOf(
      owner: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>

    create(
      owner: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>
  }
}
