/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from 'ethers'
import type { Provider } from '@ethersproject/providers'
import type {
  NativeFuturePassIdentityRegistry,
  NativeFuturePassIdentityRegistryInterface,
} from '../NativeFuturePassIdentityRegistry'

const _abi = [
  {
    inputs: [
      {
        indexed: true,
        internalType: 'address',
        name: 'futurepass',
        type: 'address',
      },
      {
        indexed: true,
        internalType: 'address',
        name: 'owner',
        type: 'address',
      },
    ],
    name: 'FuturepassCreated',
    type: 'event',
  },
  {
    inputs: [
      {
        internalType: 'address',
        name: 'owner',
        type: 'address',
      },
    ],
    name: 'futurepassOf',
    outputs: [
      {
        internalType: 'address',
        name: '',
        type: 'address',
      },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [
      {
        internalType: 'address',
        name: 'owner',
        type: 'address',
      },
    ],
    name: 'create',
    outputs: [
      {
        internalType: 'address',
        name: '',
        type: 'address',
      },
    ],
    stateMutability: 'nonpayable',
    type: 'function',
  },
] as const

export class NativeFuturePassIdentityRegistry__factory {
  static readonly abi = _abi
  static createInterface(): NativeFuturePassIdentityRegistryInterface {
    return new utils.Interface(
      _abi
    ) as NativeFuturePassIdentityRegistryInterface
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): NativeFuturePassIdentityRegistry {
    return new Contract(
      address,
      _abi,
      signerOrProvider
    ) as NativeFuturePassIdentityRegistry
  }
}
