name: Sanity Check
'on':
  push:
    branches:
      - '**'
jobs:
  build-all:
    timeout-minutes: 20
    runs-on: [self-hosted, Linux, X64, fv-ubuntu, default]
    env:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
    steps:
      - name: Set .npmrc
        run: |
          rm -f ~/.npmrc
          touch ~/.npmrc
          echo '//registry.npmjs.org/:_authToken="${NPM_TOKEN}"' >> ~/.npmrc

      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '18.19.1'
          architecture: 'x64'

      - uses: pnpm/action-setup@v2
        name: Install pnpm
        with:
          version: 8
          run_install: false

      - name: Get pnpm store directory
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

      - name: Setup pnpm cache
        uses: actions/cache@v3
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: pnpm install --frozen-lockfile=true --strict-peer-dependencies=true

      - name: Clear NX cache
        run: rm -rf ./node_modules/.cache/nx

      - name: Build All
        run: pnpm build:all

      - name: Test
        run: pnpm test
